### ISSUE TITLE
YAML file needs to be different on Linux and Mac

### ISSUE THREAD

**Issue by Ninjani** [out-of-cheese-error/the-way#15]
Subcommand argument description:
* In Mac
```yaml
        - on:
            long: on
            value_name: DATE
            help: "Snippets on <DATE>"
```

* In Linux
```yaml
        - on:
            long: on
            value_name: DATE
            about: "Snippets on <DATE>"
```
help doesn't work on Linux and about doesn't work on Mac when building from source
