### ISSUE TITLE
Indexed required argument not working

### ISSUE THREAD

**Issue by Ninjani** [out-of-cheese-error/the-way#16]
Previously, writing:
```yaml
- import:
      about: "Imports code snippets from a JSON file"
      display_order: 2
      args:
        - json:
            index: 1
            short: j
            value_name: JSON_FILE
            takes_value: true
            required: true
            help: "filename to import snippets from"
```
would allow a user to call `the-way import filename` without having to write `the-way import -j filename`. This seems to be broken now. Had to remove the `index: 1` and use the more verbose call.

**Comment by Ninjani** [comment]
Never mind, works now, I'm stupid.
```yaml
- import:
      about: "Imports code snippets from a JSON file"
      display_order: 2
      args:
        - json:
            index: 1
            value_name: JSON_FILE
            takes_value: true
```
